name: CD
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SSHPASS: "Guigui2021"

    steps:
      - uses: actions/checkout@v2
      
      - name: APT UPDATE and INSTALL SSHPASS
        run: 
          sudo apt update && sudo apt install sshpass
          
      - name: Marc
        run: 
          sshpass -e ssh -o stricthostkeychecking=no "rq1s0_guigui"@"rq1s0.ftp.infomaniak.com"
          "cd sites/zimboo.ch/ &&
          git pull &&
          composer install &&
          php bin/console d:m:m -n"
