name: CD
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SSHPASS: ${{ secrets.ZAPP_PASS }}

    steps:
      - uses: actions/checkout@v2
      
      - name: APT UPDATE and INSTALL SSHPASS
        run: 
          sudo apt update && sudo apt install sshpass
          
      - name: MarcGuillaume
        run: 
          sshpass -e ssh -o stricthostkeychecking=no ${{ secrets.ZAPP_USER }}@${{ secrets.ZAPP_HOST }}
          "cd ~/sites/zimboo.ch/ &&
          git pull &&
          composer install &&
          php bin/console d:m:m -n"
